{{- if .Values.networkFulfillment.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: network-fulfillment-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
data:
  {{- range $key, $val := .Values.networkFulfillment.config }}
  {{- if $val }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: network-fulfillment-ig
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac.labels" . | nindent 4 }}
    osac.openshift.io/project: osac-aap
type: Opaque
data:
  {{- range $key, $val := .Values.networkFulfillment.secret }}
  {{- if $val }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
